### ISSUE TITLE
Remove down direction for winch

### ISSUE THREAD

**Issue by docprofsky** [TeamCautionRobotics/2017-FRC-robot#10]
The winch has a ratchet, which means running the in reverse should not be possible.

**Comment by RiverApril** [comment]
Does it not work if the motor runs in the wrong direction? If so, then it may be good to have both directions as controls incase it is accidentally inverted in the wiring.

**Comment by docprofsky** [comment]
Since there is a ratchet, I do not want the ability to run the motor in opposition to the ratchet. If the wiring is backwards, the value can be changed in the `Winch` class or the wiring can be reversed.
