### ISSUE TITLE
Add human player light

### ISSUE THREAD

**Issue by docprofsky** [TeamCautionRobotics/2017-FRC-robot#20]

**Comment by docprofsky** [comment]
@manff What should the buttons be to activate the light?
Currently, the left and right triggers are used. I am not sure which corresponds to which.

**Comment by ConnorNail** [comment]
The left trigger should be used to activate the gear light (Press and hold not toggle)
Whenever the epiglottis is raised the light for the balls should be on (Override gear light)

**Comment by docprofsky** [comment]
Closed by #27
