### ISSUE TITLE
Clean Up the Auto Missions

### ISSUE THREAD

**Issue by TaeSeanDo** [TeamCautionRobotics/2017-FRC-robot#36]
We need to remove the auto missions that we do not use or do not work. We have quite a few auto missions, which makes it hard to find the correct one.

**Comment by docprofsky** [comment]
From @TaeSeanDo: Comment out "missionRight" to avoid confusion; that one is old.

**Comment by docprofsky** [comment]
Also, we should remove the commented commands in the missions.

**Comment by docprofsky** [comment]
This is done in `autonomous-calibration`.
