### ISSUE TITLE
Clean up code comments and warnings

### ISSUE THREAD

**Issue by docprofsky** [TeamCautionRobotics/2017-FRC-robot#39]
Currently there are commented code and some (9) warnings. The commented code should be removed or it necessity indicated and the warnings should be resolved. Also, there are two TODOs that can be removed.

Close when
- [x] The commented code has been removed or addressed.
- [x] TODOs have been addressed.
- [x] The warnings have been resolved or addressed.

**Comment by matheuscr30** [comment]
I wanna do this, can I?

**Comment by docprofsky** [comment]
Sorry, but we mainly use this for our team. Thanks for the offer, but it has been fixed in #43.
