### ISSUE TITLE
Add Controls for Door Pistons

### ISSUE THREAD

**Issue by docprofsky** [TeamCautionRobotics/2017-FRC-robot#7]
- [x]  Port 2 – Gear Chute
- [x]  Port 3 – Outfeed door
- [x]  Port 4 – Infeed door

### Controls:
- [ ] Load fuel: raise chute, close outfeed, open infeed
- [ ] Dispense fuel: open outfeed, open infeed

**Comment by docprofsky** [comment]
@manff What buttons should the load and dispense fuel buttons be on?

**Comment by ConnorNail** [comment]
Load fuel: Right Bumper
Dispense fuel: Left Bumper

**Comment by docprofsky** [comment]
Should load and dispense also run the outfeed motor?

**Comment by ConnorNail** [comment]
No I would have it just set the pneumatics to the correct position.
